# -*- coding: utf-8 -*-

from openerp import models, fields, api,_

class backend_auftraege(models.Model):
    _name='backend.auftraege'
    
    name=fields.Char('name')
    Mandant=fields.Many2one("backend.mandanten", string="Mandant")
    Buchungsdatum=fields.Char("Buchungsdatum")
    Paket=fields.Integer("Paket")
    Start=fields.Char("Start")
    Ende=fields.Char("Ende")
    Umsatz=fields.Char("Umsatz")
    Bruttoeinnahmen=fields.Char("Bruttoeinnahmen")
    Arbeitnehmer=fields.Integer("Arbeitnehmer")
    GebuehrMonatSonst=fields.Char("GebuehrMonatSonst")
    GebuehrMonatBetriebSt=fields.Char("GebuehrMonatBetriebSt")
    GebuehrMonatFiBu=fields.Char("GebuehrMonatFiBu")
    GebuehrMonatFiBuUeberw=fields.Char("GebuehrMonatFiBuUeberw")
    GebuehrEinmalSonst=fields.Char("GebuehrEinmalSonst")
    GebuehrEinmalBetriebSt=fields.Char("GebuehrEinmalBetriebSt")
    GebuehrEinmalFiBu=fields.Char("GebuehrEinmalFiBu")
    GebuehrEinmalFiBuUeberw=fields.Char("GebuehrEinmalFiBuUeberw")
    GebuehrJahrSonst=fields.Char("GebuehrJahrSonst")
    GebuehrJahrBetriebSt=fields.Char("GebuehrJahrBetriebSt")
    GebuehrJahrFiBu=fields.Char("GebuehrJahrFiBu")
    GebuehrJahrFiBuUeberw=fields.Char("GebuehrJahrFiBuUeberw")
    GebuehrMonat=fields.Char("GebuehrMonat")
    GebuehrEinmal=fields.Char("GebuehrEinmal")
    GebuehrJahr=fields.Char("GebuehrJahr")
    Bemerkung=fields.Text("Bemerkung")
    Start1=fields.Char("Start1")
    Ende1=fields.Char("Ende1")
    Umsatz1=fields.Char("Umsatz1")
    Bruttoeinnahmen1=fields.Char("Bruttoeinnahmen1")
    Arbeitnehmer1=fields.Integer("Arbeitnehmer1")
    GebuehrMonatSonst1=fields.Char("GebuehrMonatSonst1")
    GebuehrMonatBetriebSt1=fields.Char("GebuehrMonatBetriebSt1")
    GebuehrMonatFiBu1=fields.Char("GebuehrMonatFiBu1")
    GebuehrMonatFiBuUeberw1=fields.Char("GebuehrMonatFiBuUeberw1")
    GebuehrEinmalSonst1=fields.Char("GebuehrEinmalSonst1")
    GebuehrEinmalBetriebSt1=fields.Char("GebuehrEinmalBetriebSt1")
    GebuehrEinmalFiBu1=fields.Char("GebuehrEinmalFiBu1")
    GebuehrEinmalFiBuUeberw1=fields.Char("GebuehrEinmalFiBuUeberw1")
    GebuehrJahrSonst1=fields.Char("GebuehrJahrSonst1")
    GebuehrJahrBetriebSt1=fields.Char("GebuehrJahrBetriebSt1")
    GebuehrJahrFiBu1=fields.Char("GebuehrJahrFiBu1")
    GebuehrJahrFiBuUeberw1=fields.Char("GebuehrJahrFiBuUeberw1")
    FiBuAufSage=fields.Boolean("FiBuAufSage", default=False)
    FiBuAufSage1=fields.Boolean("FiBuAufSage1", dafault=False)
    Ersteller=fields.Char("Ersteller")
    AngelegtAm=fields.Char("AngelegtAm")
    AngelegtVon=fields.Char("AngelegtVon")
    Auftragswert=fields.Char("Auftragswert")
    DatenOK=fields.Boolean("DatenOK", default=False)
